### ISSUE TITLE
Quarkus 3

### ISSUE THREAD

**Issue by bpasson** [quarkiverse/quarkus-rabbitmq-client#146]
Quarkus 3 is on the horizon and we should make sure we are compatible. See https://github.com/quarkiverse/quarkiverse/wiki/Migrating-to-Quarkus-3.x for more information on how to migrate.

**Comment by lfarkas** [comment]
now as the current latest release is quarkus 3 there is not any working quarkus-rabbitmq-client. is there any plan to fix it?

**Comment by gsmet** [comment]
I created https://github.com/quarkiverse/quarkus-rabbitmq-client/pull/159

**Comment by bpasson** [comment]
Release will come next week.
