### ISSUE TITLE
Implement multiple configurations - RabbitMQClientConfig

### ISSUE THREAD

**Issue by frjrosas** [quarkiverse/quarkus-rabbitmq-client#15]
Hello, first of all thank you very much for all the hard work you're making with this Rabbitmq adapter for quarkus, I was reading the code and I want to know if is possible to add support to have multiple sources for the **RabbitMQClientConfig** class. Rigth now the RabbitMQClient has the following bean creation.

```
RabbitMQClientImpl(RabbitMQClientConfig config, TlsConfig tlsConfig, ManagedExecutor managedExecutor) {
        this.config = config;
        this.tlsConfig = tlsConfig;
        this.managedExecutor = managedExecutor;
        this.connections = new HashMap();
    }
```

I want to know if is possible to implement something like this 

```
RabbitMQClientImpl(Map<String, RabbitMQClientConfig> config, TlsConfig tlsConfig, ManagedExecutor managedExecutor) {
        this.config = config;
        this.tlsConfig = tlsConfig;
        this.managedExecutor = managedExecutor;
        this.connections = new HashMap();
    }
```

Using this approach several instance of RabbitMQClientConfig can be created using this method:

```
public RabbitMQClientConfig getProperty(String name){
    String key = "quarkus.rabbitmqclient";
    if(Objects.nonNull(name) && !name.isEmpty() && !name.isBlank()){
      key += "." + name;
    }
    return ConfigProvider.getConfig().getValue(key, RabbitMQClientConfig.class);
}
```

instead of using this:

```
@ConfigRoot(name = "rabbitmqclient", phase = ConfigPhase.RUN_TIME)
public class RabbitMQClientConfig { ... }
```

and when the method `RabbitMQClient#connect(String name)` is called then the `RabbitMQClientConfig` used could be pointing to the quarkus.rabbitmqclient.config-name property.

If you see as something that can be implemented please, I wanna read comments and your plan so you can guide me to implement something to cover this use case.

**Comment by bpasson** [comment]
@frjrosas if I am correct, you would like to have multiple configured clients? In itself it is something we can support. I would suggest to support it in the same way other extensions already do this and do it as follows.

```
@Inject
RabbitMQClient rabbitMQClient

@Inject
@RabbitMQClient("other")
RabbitMQCleint otherRabbitMQClient
```

Which would then be backed by the following configuration.

```
quarkus.rabbitmqclient.virtual-host=/vhost
quarkus.rabbitmqclient.username=rabbitmq
quarkus.rabbitmqclient.password=rabbitmq
quarkus.rabbitmqclient.hostname=somehost
quarkus.rabbitmqclient.port=1234

quarkus.rabbitmqclient.other.virtual-host=/vhost
quarkus.rabbitmqclient.other.username=rabbitmq
quarkus.rabbitmqclient.other.password=rabbitmq
quarkus.rabbitmqclient.other.hostname=somehost
quarkus.rabbitmqclient.other.port=1234
```

Would this cover your usecase?

**Comment by frjrosas** [comment]
First of all thanks for the quick reply, yes essentially that's essentially what I'm looking for. Is this implemented already? Once thank you very much for support.

**Comment by bpasson** [comment]
@frjrosas have a look at PR #16 and see it this covers your use-case completely.

**Comment by frjrosas** [comment]
Hello @bpasson, yes sir pretty much thanks for the support!
