### ISSUE TITLE
How rabbitmq cluster configuration works

### ISSUE THREAD

**Issue by Nikochian** [quarkiverse/quarkus-rabbitmq-client#151]
How rabbitmq cluster configuration works

**Comment by bpasson** [comment]
Assuming you want to configure multiple brokers to connect too. See [Broker addresses for creating connections](https://quarkiverse.github.io/quarkiverse-docs/quarkus-rabbitmq-client/dev/index.html#quarkus-rabbitmqclient_quarkus.rabbitmqclient.addresses-broker-addresses-for-creating-connections) in the documentation.

When connecting to a single RabbitMQ instance it can be simplified to a hostname and a portname, see the [documentation and examples](https://quarkiverse.github.io/quarkiverse-docs/quarkus-rabbitmq-client/dev/index.html)

**Comment by Nikochian** [comment]
Thank you very much, solved
