### ISSUE TITLE
Quarkus 2.0 Version

### ISSUE THREAD

**Issue by luneo7** [quarkiverse/quarkus-rabbitmq-client#39]
I saw that there is the CR3 version that targets Quarkus 2.0, will there be a final version?

**Comment by bpasson** [comment]
It is almost done. Just a few more things that need checking.

**Comment by bpasson** [comment]
I tested it against Quarkus 2.1.0.CR1 and made a new pre-release [0.4.0.CR1](https://github.com/quarkiverse/quarkus-rabbitmq-client/releases/tag/0.4.0.CR1). Once Quarkus 2.1.0 final is released I will make a production release.
