### ISSUE TITLE
Extension as SmallRye Connector.

### ISSUE THREAD

**Issue by belkevglaz** [quarkiverse/quarkus-rabbitmq-client#45]
Hi, @bpasson 

It is possible to wrap your extension as SmallRye Reactive Messaging Connector, like `smallrye-kafka` ? Something like `smallrye-rabbitmq`. 

The existing `smallrye-amqp` connector is extremely non-functional for Rabbit ( I supposing you know about it )

Thanks.

**Comment by bpasson** [comment]
@belkevglaz The SmallRye Reactive Messaging community has already started work on a RabbitMQ connector. See The https://github.com/smallrye/smallrye-reactive-messaging project. You might have to ask there to see when it will become available. Closing this issue.
