### ISSUE TITLE
Enable metrics collection

### ISSUE THREAD

**Issue by laurentperez** [quarkiverse/quarkus-rabbitmq-client#72]
Hello

Would it be possible to add io.quarkiverse.micrometer.registry:quarkus-micrometer-registry support to let the client send metrics by default ?

Sample metrics : messages consumed, acked, delivered

**Comment by bpasson** [comment]
Thank you for taking the time to create this ticket. Adding metrics should be possible, as the RabbitMQ client itself uses micrometer support. I expect it to be pretty straight forward to connect it to quarkus-micrometer-registry. Would you mind submitting a PR so we can go from there?

**Comment by bpasson** [comment]
Started work to get this included.

**Comment by bpasson** [comment]
This will go live with 0.5.0.Final.
