### ISSUE TITLE
Support disabling clients  

### ISSUE THREAD

**Issue by bpasson** [quarkiverse/quarkus-rabbitmq-client#73]
To be able to support use-cases where the default client is not needed, it should be possible to disable the default client. Clients currently are configured using properties like:

```
quarkus.rabbitmqclient.virtual-host=/
quarkus.rabbitmqclient.username=guest
quarkus.rabbitmqclient.password=guest
quarkus.rabbitmqclient.hostname=localhost
quarkus.rabbitmqclient.port=5672

quarkus.rabbitmqclient."<name>".virtual-host=/
quarkus.rabbitmqclient."<name>".username=guest
quarkus.rabbitmqclient."<name>".password=guest
quarkus.rabbitmqclient."<name>".hostname=localhost
quarkus.rabbitmqclient."<name>".port=5672
```
The idea is to add a new build time property `quarkus.rabbitmqclient.enabled` and `quarkus.rabbitmq."<name>".enabled` with a default value of `true` to determine if a client needs to be created.

**Comment by janyyy** [comment]
Hi，Bas Passon
How can I use the tool in service class，can you write some demos?

**Comment by bpasson** [comment]
@janyyy An example is shown in the README.md in the root of the repository. There is not more to it. Add the extension to your Quarkus application, configure the properties to point to your RabbitMQ installation and you are good to go.
