### ISSUE TITLE
About RabbmtMQ cluster connection

### ISSUE THREAD

**Issue by janyyy** [quarkiverse/quarkus-rabbitmq-client#90]
Does it support connecting to RabbitMQ clusters like Spring does? Configure as shown below

![image](https://user-images.githubusercontent.com/27274865/153797681-2483c6ca-6d65-4451-951a-bedf84ceaf48.png)

**Comment by bpasson** [comment]
@janyyy it is possible to define an arbitrary amount of brokers as follows on a per client base.

```properties
quarkus.rabbitmqclient.addresses.broker1.hostname=host1
quarkus.rabbitmqclient.addresses.broker1.port=5672
quarkus.rabbitmqclient.addresses.broker2.hostname=host2
quarkus.rabbitmqclient.addresses.broker2.port=5672

quarkus.rabbitmqclient.otherclient.addresses.broker1.hostname=host1
quarkus.rabbitmqclient.otherclient.addresses.broker1.port=5672
quarkus.rabbitmqclient.otherclient.addresses.broker2.hostname=host2
quarkus.rabbitmqclient.otherclient.addresses.broker2.port=5672
```

When you specify the addresses of the broker like this, the normal properties seen below are ignored.
```properties
quarkus.rabbitmqclient.hostname=host1
quarkus.rabbitmqclient.port=5672

quarkus.rabbitmqclient.otherclient.hostname=host1
quarkus.rabbitmqclient.otherclient.port=5672
```
Does this cover your use-case?

**Comment by bpasson** [comment]
@janyyy You can specify an unlimited amount of brokers for a single client. This is exactly like you would do it in spring, it is just configured a bit differently but it should cover your use-case. Give it a go. If it doesn't work as expected supply the feedback in this ticket and we can see how to go from there.

**Comment by janyyy** [comment]
Thanks, The configure of `address` it's normal work. I think you can write it in `README.md`
