### ISSUE TITLE
Add support for graceful shutdown

### ISSUE THREAD

**Issue by bpasson** [quarkiverse/quarkus-rabbitmq-client#93]
Right now we shutdown RabbitMQ clients immediately when Quarkus starts shutting down. This might be a bit rough for some use-cases. It makes sense to support graceful-shutdown.

See https://quarkus.io/guides/lifecycle#graceful-shutdown and https://github.com/quarkusio/quarkus/blob/main/extensions/vertx-http/deployment/src/main/java/io/quarkus/vertx/http/deployment/VertxHttpProcessor.java on how it is implemented for HTTP requests.

**Comment by bwijsmuller** [comment]
Can we just use #gracefulShutdown(@Observes ShutdownEvent event) to do an #awaitTermination() on the executorService used by the clients?
Or will #destroy be called during all this? (meaning we should perhaps just put it there?)

**Comment by bwijsmuller** [comment]
probably we need to register a shutdownListener for each connection and use a countDownLatch to wait for all to have disconnected
