### ISSUE TITLE
Connecto to rabbitmq cluster

### ISSUE THREAD

**Issue by hectorlicea** [quarkiverse/quarkus-rabbitmq-client#94]
How could I connect to a rabbitmq cluster?

**Comment by stephane-drogou** [comment]
Hello, I wrote a microservice in quarkus with this extension to connect a rabbitmq cluster. I declared the queues as quorum queue.
Here my configuration in  application.properties :
quarkus.rabbitmqclient.virtual-host=/
quarkus.rabbitmqclient.username= ****
quarkus.rabbitmqclient.password=****
quarkus.rabbitmqclient.hostname=rabbitmq
quarkus.rabbitmqclient.port=5672

Then when I statrted the docker container I declared the host rabbiqmq to the good node of the cluster.

It works fine. I have 6 instances of my service connected to 3 nodes of rabbitmq cluster.

I hope this will help

**Comment by bpasson** [comment]
Assuming the given answer resolved the issue due to lack of feedback. Closing issue.
